### ISSUE TITLE
Prod version does not work (

### ISSUE THREAD

**Issue by Romick2005** [SebMenozzi/walkie-talkie-iOS-app#1]
After pressing on button, it turn on and then off. So not manage to make it work from AppStore. Is there smth that was changed during that time, that broke the app itself?

https://apps.apple.com/ua/app/walkie-talkie-do-you-copy/id1493452470?l=uk

**Comment by SebMenozzi** [comment]
Hey @Romick2005, been 5yrs I have not touch the app lol
